using System.ComponentModel;
using System.Windows.Controls;
using System.Windows.Data;
using Genius.Atom.UI.Forms.Controls.AutoGrid.Behaviors;
using Microsoft.Xaml.Behaviors;

namespace Genius.Atom.UI.Forms.Controls.AutoGrid;

public sealed class AttachingBehavior : Behavior<DataGrid>
{
    private readonly Queue<AutoGridColumnContext> _contextsToPostProcess = new();
    private bool? _showOnlyBrowsable;

    private static readonly IAutoGridColumnBehavior[] _columnBehaviors;

    static AttachingBehavior()
    {
        _columnBehaviors = new IAutoGridColumnBehavior[] {
            // Column type changers:
            new ColumnTagEditorBehavior(),
            new ColumnButtonBehavior(),
            new ColumnWithImageBehavior(),
            new ColumnComboBoxBehavior(),
            new ColumnAttachedViewBehavior(),

            // Binding changers:
            new ColumnConverterBehavior(),
            new ColumnFormattingBehavior(),
            new ColumnNullableBehavior(),

            // Style changers:
            new ColumnTooltipBehavior(),
            new ColumnStylingBehavior(),
            new ColumnValidationBehavior(),

            // Misc:
            new ColumnHeaderNameBehavior(),
            new ColumnReadOnlyBehavior(),
            new ColumnDisplayIndexBehavior(),
            new ColumnAutoWidthBehavior()
        };
    }

    protected override void OnAttached()
    {
        AssociatedObject.AutoGenerateColumns = true;
        AssociatedObject.AutoGeneratingColumn += OnAutoGeneratingColumn;
        AssociatedObject.AutoGeneratedColumns += OnAutoGeneratedColumns;

        AssociatedObject.AddingNewItem += OnAddingNewItem;

        var dpd = DependencyPropertyDescriptor.FromProperty(DataGrid.ItemsSourceProperty, typeof(DataGrid));
        dpd?.AddValueChanged(AssociatedObject, OnItemsSourceChanged);

        base.OnAttached();
    }

    private void OnAddingNewItem(object? sender, AddingNewItemEventArgs e)
    {
        var listItemType = Helpers.GetListItemType(AssociatedObject.ItemsSource);
        var factoryTypeAttr = listItemType.GetCustomAttributes(false)
            .OfType<CustomFactoryAttribute>()
            .FirstOrDefault();

        if (factoryTypeAttr is null)
        {
            e.NewItem = Activator.CreateInstance(listItemType);
            return;
        }

        var builder = Module.ServiceProvider.GetService(factoryTypeAttr.FactoryType);
        if (builder is null)
        {
            throw new InvalidOperationException($"Cannot create instance of factory type {factoryTypeAttr.FactoryType}");
        }

        e.NewItem = builder.GetType().GetMethod(factoryTypeAttr.CreateMethod)!.Invoke(builder, Array.Empty<object>());
    }

    private void OnItemsSourceChanged(object? sender, EventArgs e)
    {
        if (AssociatedObject.ItemsSource == null)
        {
            return;
        }

        AssignRowStyle();

        var listItemType = Helpers.GetListItemType(AssociatedObject.ItemsSource);
        if (AssociatedObject.SelectionMode == DataGridSelectionMode.Extended &&
            typeof(ISelectable).IsAssignableFrom(listItemType))
        {
            BindIsSelected();
        }

        if (typeof(IEditable).IsAssignableFrom(listItemType))
        {
            BindIsEditing();
        }
    }

    private void OnAutoGeneratingColumn(object? sender, DataGridAutoGeneratingColumnEventArgs e)
    {
        var context = new AutoGridColumnContext(AssociatedObject, e, (PropertyDescriptor) e.PropertyDescriptor);

        if (!IsBrowsable(context))
        {
            e.Cancel = true;
            return;
        }

        var ignoreProperties = new [] {
            nameof(IHasDirtyFlag.IsDirty),
            nameof(ISelectable.IsSelected),
            nameof(IEditable.IsEditing),
            nameof(INotifyDataErrorInfo.HasErrors)
        };

        if (ignoreProperties.Contains(e.PropertyName)
            || context.GetAttribute<GroupByAttribute>() is not null)
            //|| typeof(ICollection).IsAssignableFrom(context.Property.PropertyType))
        {
            e.Cancel = true;
            return;
        }

        foreach (var columnBehavior in _columnBehaviors)
        {
            columnBehavior.Attach(context);
        }

        WpfHelpers.EnableSingleClickEditMode(e.Column);

        if (context.GetPostProcessingActions().Any())
        {
            _contextsToPostProcess.Enqueue(context);
        }
    }

    private void OnAutoGeneratedColumns(object? sender, EventArgs e)
    {
        while (_contextsToPostProcess.Count > 0)
        {
            var context = _contextsToPostProcess.Dequeue();
            foreach (var postProcessing in context.GetPostProcessingActions())
            {
                postProcessing();
            }
        }
    }

    private bool IsBrowsable(AutoGridColumnContext context)
    {
        _showOnlyBrowsable ??= context.Property.ComponentType.GetCustomAttributes(false)
            .Any(x => x is ShowOnlyBrowsableAttribute b && b.OnlyBrowsable);

        var browsable = context.GetAttribute<BrowsableAttribute>();
        return (!_showOnlyBrowsable.Value || browsable?.Browsable == true)
            && (_showOnlyBrowsable.Value || browsable?.Browsable != false);
    }

    private void BindIsSelected()
    {
        var binding = new Binding(nameof(ISelectable.IsSelected));
        AssociatedObject.RowStyle.Setters.Add(new Setter(DataGrid.IsSelectedProperty, binding));
    }

    private void BindIsEditing()
    {
        var binding = new Binding(nameof(IEditable.IsEditing));
        AssociatedObject.RowStyle.Setters.Add(new Setter(Properties.IsEditingProperty, binding));

        AssociatedObject.BeginningEdit += (sender, e) =>
        {
            if (e.Row.Item is IEditable editable)
            {
                e.Row.SetValue(Properties.IsEditingHandlingSuspendedProperty, true);
                editable.IsEditing = true;
                e.Row.SetValue(Properties.IsEditingHandlingSuspendedProperty, false);
            }
        };
        AssociatedObject.RowEditEnding += (sender, e) =>
        {
            if (e.Row.Item is IEditable editable)
            {
                e.Row.SetValue(Properties.IsEditingHandlingSuspendedProperty, true);
                editable.IsEditing = false;
                e.Row.SetValue(Properties.IsEditingHandlingSuspendedProperty, false);
            }
        };
    }

    private void AssignRowStyle()
    {
        AssociatedObject.RowStyle = new Style {
            TargetType = typeof(DataGridRow),
            BasedOn = (Style) AssociatedObject.FindResource("MahApps.Styles.DataGridRow")
        };
    }
}
