name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
#  release:
#    types: [published]

jobs:
  build:

    runs-on: windows-latest
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        source-url: https://nuget.pkg.github.com/hwndmaster/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --verbosity normal --logger="trx;logfilename=TestResults.trx" #--verbosity normal
    - name: Reporting
      uses: dorny/test-reporter@v1
      if: success() || failure() # run this step even if previous step failed
      with:
        name: 'Test results report'
        reporter: 'dotnet-trx'
        path: '**/TestResults/TestResults.trx'
        only-summary: 'true'
        max-annotations: '10'
        fail-on-error: 'true'
        list-suites: 'failed'
        list-tests: 'failed'
    - name: Pack Data
      run: dotnet pack Atom.Data/Atom.Data.csproj --configuration Release
    - name: Pack Infrastructure
      run: dotnet pack Atom.Infrastructure/Atom.Infrastructure.csproj --configuration Release
    - name: Pack Infrastructure.TestingUtil
      run: dotnet pack Atom.Infrastructure.TestingUtil/Atom.Infrastructure.TestingUtil.csproj --configuration Release
    - name: Pack UI.Forms
      run: dotnet pack Atom.UI.Forms/Atom.UI.Forms.csproj --configuration Release
    - name: Pack UI.Forms.TestingUtil
      run: dotnet pack Atom.UI.Forms.TestingUtil/Atom.UI.Forms.TestingUtil.csproj --configuration Release
    - name: Pack Reporting
      run: dotnet pack Atom.Reporting/Atom.Reporting.csproj --configuration Release
    - name: Pack Reporting.UI
      run: dotnet pack Atom.Reporting.UI/Atom.Reporting.UI.csproj --configuration Release
    - name: Pack Build
      run: dotnet pack Atom.Build/Atom.Build.csproj --configuration Release
    - name: Publish packages to GPR
      run: dotnet nuget push **/*.nupkg --skip-duplicate --api-key ${{ secrets.GITHUB_TOKEN }}
