name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
#  release:
#    types: [published]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Pack Infrastructure
      run: dotnet pack Atom.Infrastructure/Atom.Infrastructure.csproj --output nuget-packages --configuration Release
    - name: Pack UI.Forms
      run: dotnet pack Atom.UI.Forms/Atom.UI.Forms.csproj --output nuget-packages --configuration Release
    - name: Publish packages to nuget.org
      run: dotnet nuget push **/*.nupkg --api-key ${NUGET_AUTH_TOKEN} --skip-duplicate --source https://api.nuget.org/v3/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_API_KEY }}
