name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
#  release:
#    types: [published]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        source-url: https://nuget.pkg.github.com/hwndmaster/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Pack Data
      run: dotnet pack Atom.Data/Atom.Data.csproj --configuration Release
    - name: Pack Infrastructure
      run: dotnet pack Atom.Infrastructure/Atom.Infrastructure.csproj --configuration Release
    - name: Pack Infrastructure.TestingUtil
      run: dotnet pack Atom.Infrastructure.TestingUtil/Atom.Infrastructure.TestingUtil.csproj --configuration Release
    - name: Pack UI.Forms
      run: dotnet pack Atom.UI.Forms/Atom.UI.Forms.csproj --configuration Release
    - name: Pack UI.Forms.TestingUtil
      run: dotnet pack Atom.UI.Forms.TestingUtil/Atom.UI.Forms.TestingUtil.csproj --configuration Release
    - name: Publish packages to GPR
      run: dotnet nuget push **/*.nupkg --skip-duplicate
